import jsPDF from "jspdf";
import { TIME_WINDOW_LABELS, type TimeWindow } from "@/app/lib/constants";

interface PDFStop {
  sortOrder: number;
  ntaName: string | null;
  borough: string | null;
  timeWindow: string;
  demandScore: number | null;
  nearestSubwayMeters: number | null;
  notes: string | null;
}

interface PDFRouteData {
  name: string;
  vertical: string;
  date: string | null;
  status: string;
  stops: PDFStop[];
  avgDemand: number;
}

const VERTICAL_LABELS: Record<string, string> = {
  coffee: "Coffee / Beverage",
  food_truck: "Food Truck",
  retail: "Retail Pop-Up",
  political: "Political Canvass",
  events: "Event Planning",
  custom: "Custom",
};

export function generateRoutePDF(route: PDFRouteData): jsPDF {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  let y = margin;

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("DemandMap NYC", margin, y);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text("Route Sheet", pageWidth - margin, y, { align: "right" });
  y += 30;

  // Route title
  doc.setTextColor(0);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(route.name, margin, y);
  y += 18;

  // Route meta
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100);
  const meta = [
    `Vertical: ${VERTICAL_LABELS[route.vertical] ?? route.vertical}`,
    route.date ? `Date: ${new Date(route.date).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" })}` : null,
    `Status: ${route.status}`,
    `Stops: ${route.stops.length}`,
    `Avg Demand: ${route.avgDemand.toFixed(1)}/100`,
  ].filter(Boolean).join("  |  ");
  doc.text(meta, margin, y);
  y += 25;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 15;

  // Table header
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(80);
  const cols = [
    { label: "#", x: margin, w: 20 },
    { label: "NEIGHBORHOOD", x: margin + 25, w: 180 },
    { label: "BOROUGH", x: margin + 210, w: 80 },
    { label: "TIME WINDOW", x: margin + 295, w: 80 },
    { label: "DEMAND", x: margin + 380, w: 50 },
    { label: "SUBWAY", x: margin + 435, w: 50 },
  ];
  cols.forEach((col) => doc.text(col.label, col.x, y));
  y += 5;
  doc.setDrawColor(220);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  // Table rows
  doc.setFont("helvetica", "normal");
  doc.setTextColor(40);
  doc.setFontSize(9);

  for (const stop of route.stops) {
    if (y > 700) {
      doc.addPage();
      y = margin;
    }

    doc.text(`${stop.sortOrder + 1}`, cols[0].x, y);
    doc.text(stop.ntaName ?? "—", cols[1].x, y);
    doc.text(stop.borough ?? "—", cols[2].x, y);
    doc.text(
      TIME_WINDOW_LABELS[stop.timeWindow as TimeWindow] ?? stop.timeWindow,
      cols[3].x,
      y,
    );
    doc.text(
      stop.demandScore != null ? stop.demandScore.toFixed(1) : "—",
      cols[4].x,
      y,
    );
    doc.text(
      stop.nearestSubwayMeters != null ? `${Math.round(stop.nearestSubwayMeters)}m` : "—",
      cols[5].x,
      y,
    );

    if (stop.notes) {
      y += 12;
      doc.setFontSize(7);
      doc.setTextColor(130);
      doc.text(`Note: ${stop.notes}`, cols[1].x, y);
      doc.setFontSize(9);
      doc.setTextColor(40);
    }

    y += 18;
  }

  // Footer
  y += 10;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 15;
  doc.setFontSize(7);
  doc.setTextColor(160);
  doc.text(
    `Generated by DemandMap NYC on ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
    margin,
    y,
  );

  return doc;
}
